spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://1127.0.0.1:3306/mall?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      initial-size: 20
      max-active: 50
      min-idle: 10
      max-idle: 20
      max-wait: 10
      default-auto-commit: true
      min-evictable-idle-time-millis: 3600000
      time-between-eviction-runs-millis: 40000
      test-while-idle: true
      validation-query: select 'x'
      filters: stat,log4j,slf4j

mybatis:
  mapper-locations: classpath:mappers/*.xml

server:
  servlet:
    context-path: /mall

